# Generated by Django 5.0.3 on 2024-04-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0002_profile_account_balance'),
        ('subscriptions', '0001_initial'),
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextToVoiceUser',
            new_name='TextToSpeechUser',
        ),
    ]
